# Generated by Django 6.0.1 on 2026-04-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='iban',
            field=models.CharField(blank=True, help_text='Numéro de compte bancaire BE (IBAN)', max_length=34, null=True),
        ),
    ]
