# Generated by Django 6.0.1 on 2026-04-21 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_taxi_iban'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibiliteCoiffeuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('actif', models.BooleanField(default=True)),
                ('coiffeuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='core.coiffeuse')),
            ],
            options={
                'unique_together': {('coiffeuse', 'jour')},
            },
        ),
    ]
