# Generated by Django 6.0.1 on 2026-04-21 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_disponibilitecoiffeuse'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('traitee', models.BooleanField(default=False)),
                ('coiffeuse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demande_website', to='core.coiffeuse')),
            ],
        ),
    ]
