# Generated by Django 6.0.1 on 2026-04-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_demandewebsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxi',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxi',
            name='position_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
